export enum CategoryType {
    INCOME = 'INCOME',
    EXPENSE = 'EXPENSE',
    TRANSFER = 'TRANSFER',
    LEND = 'LEND',
    BORROW = 'BORROW',
    COLLECTING_DEBT = 'COLLECTING_DEBT',
    REPAYMENT = 'REPAYMENT',
}