export enum TransactionType {
    INCOME = "INCOME",
    EXPENSE = "EXPENSE",
    TRANSFER = "TRANSFER",
    LEND = "LEND",
    BORROW = "BORROW",
    MODIFY_BALANCE = "MODIFY_BALANCE",
    COLLECTING_DEBT = "COLLECTING_DEBT",
    REPAYMENT = "REPAYMENT",
}