name: CI/CD Pipeline - Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build & Push Docker image
    runs_on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t dlir2404/intel-money-be:latest .

      - name: Push Docker Image
        run: |
          docker push dlir2404/intel-money-be:latest

  deploy:
    name: Deploy to server
    runs_on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull dlir2404/intel-money-backend:latest
            docker compose down
            docker compose up -d
            docker system prune -af
